# Generated by extendr: Do not edit by hand

# nolint start

#
# This file was created with the following call:
#   .Call("wrap__make_rjsonschema_wrappers", use_symbols = TRUE, package_name = "rjsonschema")

#' @usage NULL
#' @useDynLib rjsonschema, .registration = TRUE
NULL

validate_rs <- function(schema, instance, version) .Call(wrap__validate_rs, schema, instance, version)

validate_basic_rs <- function(schema, instance, version) .Call(wrap__validate_basic_rs, schema, instance, version)


# nolint end
